export const COUNTRYCONTINENTS = {
  'Andorra': 'Europe',
  'Afghanistan': 'Asia',
  'Antigua and Barbuda': 'North America',
  'Albania': 'Europe',
  'Armenia': 'Asia',
  'Angola': 'Africa',
  'Argentina': 'South America',
  'Austria': 'Europe',
  'Australia': 'Oceania',
  'Azerbaijan': 'Asia',
  'Barbados': 'North America',
  'Bangladesh': 'Asia',
  'Belgium': 'Europe',
  'Burkina Faso': 'Africa',
  'Bulgaria': 'Europe',
  'Bahrain': 'Asia',
  'Burundi': 'Africa',
  'Benin': 'Africa',
  'Brunei Darussalam': 'Asia',
  'Bolivia': 'South America',
  'Brazil': 'South America',
  'Bahamas': 'North America',
  'Bhutan': 'Asia',
  'Botswana': 'Africa',
  'Belarus': 'Europe',
  'Belize': 'North America',
  'Canada': 'North America',
  'Democratic Republic of the Congo': 'Africa',
  'Republic of the Congo': 'Africa',
  "C\u00c3\u00b4te d'Ivoire": 'Africa',
  'Chile': 'South America',
  'Cameroon': 'Africa',
  'China': 'Asia',
  'Colombia': 'South America',
  'Costa Rica': 'North America',
  'Cuba': 'North America',
  'Cape Verde': 'Africa',
  'Cyprus': 'Asia',
  'Czech Republic': 'Europe',
  'Germany': 'Europe',
  'Djibouti': 'Africa',
  'Denmark': 'Europe',
  'Dominica': 'North America',
  'Dominican Republic': 'North America',
  'Ecuador': 'South America',
  'Estonia': 'Europe',
  'Egypt': 'Africa',
  'Eritrea': 'Africa',
  'Ethiopia': 'Africa',
  'Finland': 'Europe',
  'Fiji': 'Oceania',
  'France': 'Europe',
  'Gabon': 'Africa',
  'Georgia': 'Asia',
  'Ghana': 'Africa',
  'The Gambia': 'Africa',
  'Guinea': 'Africa',
  'Greece': 'Europe',
  'Guatemala': 'North America',
  'Haiti': 'North America',
  'Guinea-Bissau': 'Africa',
  'Guyana': 'South America',
  'Honduras': 'North America',
  'Hungary': 'Europe',
  'Indonesia': 'Asia',
  'Ireland': 'Europe',
  'Israel': 'Asia',
  'India': 'Asia',
  'Iraq': 'Asia',
  'Iran': 'Asia',
  'Iceland': 'Europe',
  'Italy': 'Europe',
  'Jamaica': 'North America',
  'Jordan': 'Asia',
  'Japan': 'Asia',
  'Kenya': 'Africa',
  'Kyrgyzstan': 'Asia',
  'Kiribati': 'Oceania',
  'North Korea': 'Asia',
  'South Korea': 'Asia',
  'Kuwait': 'Asia',
  'Lebanon': 'Asia',
  'Liechtenstein': 'Europe',
  'Liberia': 'Africa',
  'Lesotho': 'Africa',
  'Lithuania': 'Europe',
  'Luxembourg': 'Europe',
  'Latvia': 'Europe',
  'Libya': 'Africa',
  'Madagascar': 'Africa',
  'Marshall Islands': 'Oceania',
  'Macedonia': 'Europe',
  'Mali': 'Africa',
  'Myanmar': 'Asia',
  'Mongolia': 'Asia',
  'Mauritania': 'Africa',
  'Malta': 'Europe',
  'Mauritius': 'Africa',
  'Maldives': 'Asia',
  'Malawi': 'Africa',
  'Mexico': 'North America',
  'Malaysia': 'Asia',
  'Mozambique': 'Africa',
  'Namibia': 'Africa',
  'Niger': 'Africa',
  'Nigeria': 'Africa',
  'Nicaragua': 'North America',
  'Netherlands': 'Europe',
  'Norway': 'Europe',
  'Nepal': 'Asia',
  'Nauru': 'Oceania',
  'New Zealand': 'Oceania',
  'Oman': 'Asia',
  'Panama': 'North America',
  'Peru': 'South America',
  'Papua New Guinea': 'Oceania',
  'Philippines': 'Asia',
  'Pakistan': 'Asia',
  'Poland': 'Europe',
  'Portugal': 'Europe',
  'Palau': 'Oceania',
  'Paraguay': 'South America',
  'Qatar': 'Asia',
  'Romania': 'Europe',
  'Russia': 'Europe',
  'Rwanda': 'Africa',
  'Saudi Arabia': 'Asia',
  'Solomon Islands': 'Oceania',
  'Seychelles': 'Africa',
  'Sudan': 'Africa',
  'Sweden': 'Europe',
  'Singapore': 'Asia',
  'Slovenia': 'Europe',
  'Slovakia': 'Europe',
  'Sierra Leone': 'Africa',
  'San Marino': 'Europe',
  'Senegal': 'Africa',
  'Somalia': 'Africa',
  'Suriname': 'South America',
  'S\u00c3\u00a3o Tom\u00c3\u00a9 and Pr\u00c3\u00adncipe': 'Africa',
  'Syria': 'Asia',
  'Togo': 'Africa',
  'Thailand': 'Asia',
  'Tajikistan': 'Asia',
  'Turkmenistan': 'Asia',
  'Tunisia': 'Africa',
  'Tonga': 'Oceania',
  'Turkey': 'Asia',
  'Trinidad and Tobago': 'North America',
  'Tuvalu': 'Oceania',
  'Tanzania': 'Africa',
  'Ukraine': 'Europe',
  'Uganda': 'Africa',
  'United States of America': 'North America',
  'Uruguay': 'South America',
  'Uzbekistan': 'Asia',
  'Vatican City': 'Europe',
  'Venezuela': 'South America',
  'Vietnam': 'Asia',
  'Vanuatu': 'Oceania',
  'Yemen': 'Asia',
  'Zambia': 'Africa',
  'Zimbabwe': 'Africa',
  'Algeria': 'Africa',
  'Bosnia & Herzegovina': 'Europe',
  'Cambodia': 'Asia',
  'Central African Republic': 'Africa',
  'Chad': 'Africa',
  'Comoros': 'Africa',
  'Croatia': 'Europe',
  'East Timor': 'Asia',
  'El Salvador': 'North America',
  'Equatorial Guinea': 'Africa',
  'Grenada': 'North America',
  'Kazakhstan': 'Asia',
  'Laos': 'Asia',
  'Federated States of Micronesia': 'Oceania',
  'Moldova': 'Europe',
  'Monaco': 'Europe',
  'Montenegro': 'Europe',
  'Morocco': 'Africa',
  'Saint Kitts and Nevis': 'North America',
  'Saint Lucia': 'North America',
  'Saint Vincent and the Grenadines': 'North America',
  'Samoa': 'Oceania',
  'Serbia': 'Europe',
  'South Africa': 'Africa',
  'Spain': 'Europe',
  'Sri Lanka': 'Asia',
  'Swaziland': 'Africa',
  'Switzerland': 'Europe',
  'United Arab Emirates': 'Asia',
  'United Kingdom': 'Europe',
  'Taiwan': 'Asia',
  'Hong Kong': 'Asia',
  'Kosovo': 'Europe',
  'Puerto Rico': 'America',
}
