import { shallowMount, createLocalVue } from '@vue/test-utils'
import VueRouter from 'vue-router'
import Status from '@/views/Status'
import { iotlab } from '@/rest'
import * as Filters from '@/filters'

jest.mock('@/rest')
iotlab.getNodes = jest.fn().mockResolvedValue([{
  "uid": "b160",
  "site": "devgrenoble",
  "x": "2",
  "mobile": 0,
  "network_address": "a8-1.devgrenoble.iot-lab.info",
  "y": "0",
  "z": "0",
  "mobility_type": " ",
  "state": "Busy",
  "camera": 0,
  "archi": "a8:at86rf231"
}, {
  "uid": "3585",
  "site": "devgrenoble",
  "x": "3",
  "mobile": 0,
  "network_address": "a8-2.devgrenoble.iot-lab.info",
  "y": "0",
  "z": "0",
  "mobility_type": " ",
  "state": "Busy",
  "camera": 0,
  "archi": "a8:at86rf231"
}, {
  "uid": "2287",
  "site": "devgrenoble",
  "x": "3",
  "mobile": 0,
  "network_address": "a8-3.devgrenoble.iot-lab.info",
  "y": "1",
  "z": "0",
  "mobility_type": " ",
  "state": "Busy",
  "camera": 0,
  "archi": "a8:at86rf231"
}, {
  "uid": "3784",
  "site": "devgrenoble",
  "x": "2",
  "mobile": 0,
  "network_address": "a8-4.devgrenoble.iot-lab.info",
  "y": "1",
  "z": "0",
  "mobility_type": " ",
  "state": "Busy",
  "camera": 0,
  "archi": "a8:at86rf231"
}, {
  "uid": "b059",
  "site": "devgrenoble",
  "x": "2",
  "mobile": 0,
  "network_address": "a8-5.devgrenoble.iot-lab.info",
  "y": "0",
  "z": "1",
  "mobility_type": " ",
  "state": "Busy",
  "camera": 0,
  "archi": "a8:at86rf231"
}, {
  "uid": "a864",
  "site": "devgrenoble",
  "x": "3",
  "mobile": 0,
  "network_address": "a8-6.devgrenoble.iot-lab.info",
  "y": "0",
  "z": "1",
  "mobility_type": " ",
  "state": "Busy",
  "camera": 0,
  "archi": "a8:at86rf231"
}, {
  "uid": "a758",
  "site": "devgrenoble",
  "x": "3",
  "mobile": 0,
  "network_address": "a8-7.devgrenoble.iot-lab.info",
  "y": "1",
  "z": "1",
  "mobility_type": " ",
  "state": "Busy",
  "camera": 0,
  "archi": "a8:at86rf231"
}, {
  "uid": " ",
  "site": "devgrenoble",
  "x": "2",
  "mobile": 0,
  "network_address": "a8-8.devgrenoble.iot-lab.info",
  "y": "1",
  "z": "1",
  "mobility_type": " ",
  "state": "Busy",
  "camera": 0,
  "archi": "a8:at86rf231"
}, {
  "uid": "b061",
  "site": "devgrenoble",
  "x": "2",
  "mobile": 0,
  "network_address": "a8-9.devgrenoble.iot-lab.info",
  "y": "2",
  "z": "0",
  "mobility_type": " ",
  "state": "Busy",
  "camera": 0,
  "archi": "a8:at86rf231"
}, {
  "uid": "c365",
  "site": "devgrenoble",
  "x": "3",
  "mobile": 0,
  "network_address": "a8-10.devgrenoble.iot-lab.info",
  "y": "2",
  "z": "0",
  "mobility_type": " ",
  "state": "Alive",
  "camera": 0,
  "archi": "a8:at86rf231"
}, {
  "uid": "9564",
  "site": "devgrenoble",
  "x": "2",
  "mobile": 0,
  "network_address": "a8-12.devgrenoble.iot-lab.info",
  "y": "3",
  "z": "0",
  "mobility_type": " ",
  "state": "Dead",
  "camera": 0,
  "archi": "a8:at86rf231"
}, {
  "uid": " ",
  "site": "devgrenoble",
  "x": "4",
  "mobile": 0,
  "network_address": "a8-17.devgrenoble.iot-lab.info",
  "y": "1",
  "z": "0",
  "mobility_type": " ",
  "state": "Busy",
  "camera": 0,
  "archi": "a8:at86rf231"
}, {
  "uid": " ",
  "site": "devgrenoble",
  "x": "5",
  "mobile": 0,
  "network_address": "des-1.devgrenoble.iot-lab.info",
  "y": "0",
  "z": "0",
  "mobility_type": " ",
  "state": "Suspected",
  "camera": 0,
  "archi": "des:wifi-cc1100"
}, {
  "uid": "b783",
  "site": "devgrenoble",
  "x": "0",
  "mobile": 0,
  "network_address": "m3-1.devgrenoble.iot-lab.info",
  "y": "0",
  "z": "0",
  "mobility_type": " ",
  "state": "Alive",
  "camera": 0,
  "archi": "m3:at86rf231"
}, {
  "uid": "9884",
  "site": "devgrenoble",
  "x": "1",
  "mobile": 0,
  "network_address": "m3-2.devgrenoble.iot-lab.info",
  "y": "0",
  "z": "0",
  "mobility_type": " ",
  "state": "Alive",
  "camera": 0,
  "archi": "m3:at86rf231"
}, {
  "uid": "8869",
  "site": "devgrenoble",
  "x": "1",
  "mobile": 0,
  "network_address": "m3-3.devgrenoble.iot-lab.info",
  "y": "1",
  "z": "0",
  "mobility_type": " ",
  "state": "Alive",
  "camera": 0,
  "archi": "m3:at86rf231"
}, {
  "uid": "1354",
  "site": "devgrenoble",
  "x": "0",
  "mobile": 0,
  "network_address": "m3-4.devgrenoble.iot-lab.info",
  "y": "1",
  "z": "0",
  "mobility_type": " ",
  "state": "Alive",
  "camera": 0,
  "archi": "m3:at86rf231"
}, {
  "uid": "c468",
  "site": "devgrenoble",
  "x": "0",
  "mobile": 0,
  "network_address": "m3-5.devgrenoble.iot-lab.info",
  "y": "0",
  "z": "1",
  "mobility_type": " ",
  "state": "Alive",
  "camera": 0,
  "archi": "m3:at86rf231"
}, {
  "uid": "9778",
  "site": "devgrenoble",
  "x": "1",
  "mobile": 0,
  "network_address": "m3-6.devgrenoble.iot-lab.info",
  "y": "0",
  "z": "1",
  "mobility_type": " ",
  "state": "Alive",
  "camera": 0,
  "archi": "m3:at86rf231"
}, {
  "uid": "2261",
  "site": "devgrenoble",
  "x": "1",
  "mobile": 0,
  "network_address": "m3-7.devgrenoble.iot-lab.info",
  "y": "1",
  "z": "1",
  "mobility_type": " ",
  "state": "Alive",
  "camera": 0,
  "archi": "m3:at86rf231"
}, {
  "uid": "c269",
  "site": "devgrenoble",
  "x": "0",
  "mobile": 0,
  "network_address": "m3-8.devgrenoble.iot-lab.info",
  "y": "1",
  "z": "1",
  "mobility_type": " ",
  "state": "Alive",
  "camera": 0,
  "archi": "m3:at86rf231"
}, {
  "uid": "1262",
  "site": "devgrenoble",
  "x": "0",
  "mobile": 0,
  "network_address": "m3-9.devgrenoble.iot-lab.info",
  "y": "2",
  "z": "0",
  "mobility_type": " ",
  "state": "Alive",
  "camera": 0,
  "archi": "m3:at86rf231"
}, {
  "uid": "8769",
  "site": "devgrenoble",
  "x": "1",
  "mobile": 0,
  "network_address": "m3-10.devgrenoble.iot-lab.info",
  "y": "2",
  "z": "0",
  "mobility_type": " ",
  "state": "Busy",
  "camera": 0,
  "archi": "m3:at86rf231"
}, {
  "uid": "8679",
  "site": "devgrenoble",
  "x": "1",
  "mobile": 0,
  "network_address": "m3-11.devgrenoble.iot-lab.info",
  "y": "3",
  "z": "0",
  "mobility_type": " ",
  "state": "Suspected",
  "camera": 0,
  "archi": "m3:at86rf231"
}, {
  "uid": "3053",
  "site": "devgrenoble",
  "x": "0",
  "mobile": 0,
  "network_address": "m3-12.devgrenoble.iot-lab.info",
  "y": "3",
  "z": "0",
  "mobility_type": " ",
  "state": "Busy",
  "camera": 0,
  "archi": "m3:at86rf231"
}, {
  "uid": "b178",
  "site": "devgrenoble",
  "x": "3",
  "mobile": 0,
  "network_address": "m3-13.devgrenoble.iot-lab.info",
  "y": "2",
  "z": "1",
  "mobility_type": " ",
  "state": "Busy",
  "camera": 0,
  "archi": "m3:at86rf231"
}, {
  "uid": "b981",
  "site": "devgrenoble",
  "x": "1",
  "mobile": 0,
  "network_address": "m3-14.devgrenoble.iot-lab.info",
  "y": "2",
  "z": "1",
  "mobility_type": " ",
  "state": "Alive",
  "camera": 0,
  "archi": "m3:at86rf231"
}, {
  "uid": " ",
  "site": "devgrenoble",
  "x": "4",
  "mobile": 0,
  "network_address": "m3-17.devgrenoble.iot-lab.info",
  "y": "0",
  "z": "0",
  "mobility_type": " ",
  "state": "Alive",
  "camera": 0,
  "archi": "m3:at86rf231"
}, {
  "uid": " ",
  "site": "devgrenoble",
  "x": "10",
  "mobile": 1,
  "network_address": "m3-18.devgrenoble.iot-lab.info",
  "y": "0",
  "z": "0",
  "mobility_type": "turtlebot2",
  "state": "Absent",
  "camera": 0,
  "archi": "m3:at86rf231"
}, {
  "uid": " ",
  "site": "devgrenoble",
  "x": "10",
  "mobile": 1,
  "network_address": "m3-19.devgrenoble.iot-lab.info",
  "y": "0",
  "z": "0",
  "mobility_type": "turtlebot2",
  "state": "Absent",
  "camera": 0,
  "archi": "m3:at86rf231"
}, {
  "uid": " ",
  "site": "devstrasbourg",
  "x": " ",
  "mobile": 0,
  "network_address": "a8-1.devstrasbourg.iot-lab.info",
  "y": " ",
  "z": " ",
  "mobility_type": " ",
  "state": "Alive",
  "camera": 0,
  "archi": "a8:at86rf231"
}, {
  "uid": " ",
  "site": "devstrasbourg",
  "x": " ",
  "mobile": 0,
  "network_address": "a8-2.devstrasbourg.iot-lab.info",
  "y": " ",
  "z": " ",
  "mobility_type": " ",
  "state": "Alive",
  "camera": 0,
  "archi": "a8:at86rf231"
}, {
  "uid": " ",
  "site": "devstrasbourg",
  "x": " ",
  "mobile": 0,
  "network_address": "wsn430-257.devstrasbourg.iot-lab.info",
  "y": " ",
  "z": " ",
  "mobility_type": " ",
  "state": "Suspected",
  "camera": 0,
  "archi": "wsn430:cc1101"
}, {
  "uid": " ",
  "site": "devstrasbourg",
  "x": " ",
  "mobile": 0,
  "network_address": "wsn430-258.devstrasbourg.iot-lab.info",
  "y": " ",
  "z": " ",
  "mobility_type": " ",
  "state": "Suspected",
  "camera": 0,
  "archi": "wsn430:cc1101"
}, {
  "uid": " ",
  "site": "devstrasbourg",
  "x": " ",
  "mobile": 0,
  "network_address": "wsn430-259.devstrasbourg.iot-lab.info",
  "y": " ",
  "z": " ",
  "mobility_type": " ",
  "state": "Suspected",
  "camera": 0,
  "archi": "wsn430:cc1101"
}, {
  "uid": " ",
  "site": "devstrasbourg",
  "x": " ",
  "mobile": 0,
  "network_address": "wsn430-260.devstrasbourg.iot-lab.info",
  "y": " ",
  "z": " ",
  "mobility_type": " ",
  "state": "Suspected",
  "camera": 0,
  "archi": "wsn430:cc1101"
}, {
  "uid": " ",
  "site": "devstrasbourg",
  "x": "0",
  "mobile": 1,
  "network_address": "m3-65.devstrasbourg.iot-lab.info",
  "y": "0",
  "z": "0",
  "mobility_type": "turtlebot2",
  "state": "Absent",
  "camera": 0,
  "archi": "m3:at86rf231"
}, {
  "uid": " ",
  "site": "devstrasbourg",
  "x": "0",
  "mobile": 1,
  "network_address": "m3-66.devstrasbourg.iot-lab.info",
  "y": "0",
  "z": "0",
  "mobility_type": "turtlebot2",
  "state": "Absent",
  "camera": 0,
  "archi": "m3:at86rf231"
}, {
  "uid": " ",
  "site": "devstrasbourg",
  "x": "0",
  "mobile": 1,
  "network_address": "m3-67.devstrasbourg.iot-lab.info",
  "y": "0",
  "z": "0",
  "mobility_type": "turtlebot2",
  "state": "Absent",
  "camera": 0,
  "archi": "m3:at86rf231"
}, {
  "uid": " ",
  "site": "devstrasbourg",
  "x": "0",
  "mobile": 1,
  "network_address": "m3-68.devstrasbourg.iot-lab.info",
  "y": "0",
  "z": "0",
  "mobility_type": "turtlebot2",
  "state": "Absent",
  "camera": 0,
  "archi": "m3:at86rf231"
}, {
  "uid": " ",
  "site": "devstrasbourg",
  "x": "0",
  "mobile": 1,
  "network_address": "m3-69.devstrasbourg.iot-lab.info",
  "y": "0",
  "z": "0",
  "mobility_type": "turtlebot2",
  "state": "Alive",
  "camera": 0,
  "archi": "m3:at86rf231"
}, {
  "uid": " ",
  "site": "devstrasbourg",
  "x": "0",
  "mobile": 1,
  "network_address": "m3-70.devstrasbourg.iot-lab.info",
  "y": "0",
  "z": "0",
  "mobility_type": "turtlebot2",
  "state": "Absent",
  "camera": 0,
  "archi": "m3:at86rf231"
}, {
  "uid": " ",
  "site": "devstrasbourg",
  "x": "0",
  "mobile": 1,
  "network_address": "m3-71.devstrasbourg.iot-lab.info",
  "y": "0",
  "z": "0",
  "mobility_type": "turtlebot2",
  "state": "Alive",
  "camera": 0,
  "archi": "m3:at86rf231"
}, {
  "uid": " ",
  "site": "devstrasbourg",
  "x": "0",
  "mobile": 1,
  "network_address": "m3-72.devstrasbourg.iot-lab.info",
  "y": "0",
  "z": "0",
  "mobility_type": "turtlebot2",
  "state": "Alive",
  "camera": 0,
  "archi": "m3:at86rf231"
}, {
  "uid": " ",
  "site": "devstrasbourg",
  "x": "0",
  "mobile": 1,
  "network_address": "m3-73.devstrasbourg.iot-lab.info",
  "y": "0",
  "z": "0",
  "mobility_type": "turtlebot2",
  "state": "Absent",
  "camera": 0,
  "archi": "m3:at86rf231"
}, {
  "uid": " ",
  "site": "devstrasbourg",
  "x": "0",
  "mobile": 1,
  "network_address": "m3-74.devstrasbourg.iot-lab.info",
  "y": "0",
  "z": "0",
  "mobility_type": "turtlebot2",
  "state": "Alive",
  "camera": 0,
  "archi": "m3:at86rf231"
}, {
  "uid": " ",
  "site": "devstrasbourg",
  "x": "0",
  "mobile": 1,
  "network_address": "m3-75.devstrasbourg.iot-lab.info",
  "y": "0",
  "z": "0",
  "mobility_type": "turtlebot2",
  "state": "Alive",
  "camera": 0,
  "archi": "m3:at86rf231"
}, {
  "uid": " ",
  "site": "devstrasbourg",
  "x": "0",
  "mobile": 1,
  "network_address": "m3-76.devstrasbourg.iot-lab.info",
  "y": "0",
  "z": "0",
  "mobility_type": "turtlebot2",
  "state": "Alive",
  "camera": 0,
  "archi": "m3:at86rf231"
}, {
  "uid": " ",
  "site": "devstrasbourg",
  "x": "0",
  "mobile": 1,
  "network_address": "m3-81.devstrasbourg.iot-lab.info",
  "y": "0",
  "z": "0",
  "mobility_type": "turtlebot2",
  "state": "Alive",
  "camera": 0,
  "archi": "m3:at86rf231"
}, {
  "uid": " ",
  "site": "devstrasbourg",
  "x": "0",
  "mobile": 1,
  "network_address": "m3-82.devstrasbourg.iot-lab.info",
  "y": "0",
  "z": "0",
  "mobility_type": "turtlebot2",
  "state": "Alive",
  "camera": 0,
  "archi": "m3:at86rf231"
}, {
  "uid": " ",
  "site": "devstrasbourg",
  "x": "0",
  "mobile": 1,
  "network_address": "m3-83.devstrasbourg.iot-lab.info",
  "y": "0",
  "z": "0",
  "mobility_type": "turtlebot2",
  "state": "Alive",
  "camera": 0,
  "archi": "m3:at86rf231"
}, {
  "uid": " ",
  "site": "devstrasbourg",
  "x": "0",
  "mobile": 1,
  "network_address": "m3-84.devstrasbourg.iot-lab.info",
  "y": "0",
  "z": "0",
  "mobility_type": "turtlebot2",
  "state": "Absent",
  "camera": 0,
  "archi": "m3:at86rf231"
}, {
  "uid": " ",
  "site": "devstrasbourg",
  "x": "0",
  "mobile": 1,
  "network_address": "m3-85.devstrasbourg.iot-lab.info",
  "y": "0",
  "z": "0",
  "mobility_type": "turtlebot2",
  "state": "Alive",
  "camera": 0,
  "archi": "m3:at86rf231"
}, {
  "uid": " ",
  "site": "devstrasbourg",
  "x": "0",
  "mobile": 1,
  "network_address": "m3-86.devstrasbourg.iot-lab.info",
  "y": "0",
  "z": "0",
  "mobility_type": "turtlebot2",
  "state": "Absent",
  "camera": 0,
  "archi": "m3:at86rf231"
}, {
  "uid": " ",
  "site": "devstrasbourg",
  "x": "0",
  "mobile": 1,
  "network_address": "m3-87.devstrasbourg.iot-lab.info",
  "y": "0",
  "z": "0",
  "mobility_type": "turtlebot2",
  "state": "Alive",
  "camera": 0,
  "archi": "m3:at86rf231"
}, {
  "uid": " ",
  "site": "devstrasbourg",
  "x": "0",
  "mobile": 1,
  "network_address": "m3-88.devstrasbourg.iot-lab.info",
  "y": "0",
  "z": "0",
  "mobility_type": "turtlebot2",
  "state": "Absent",
  "camera": 0,
  "archi": "m3:at86rf231"
}, {
  "uid": " ",
  "site": "devstrasbourg",
  "x": "0",
  "mobile": 1,
  "network_address": "m3-89.devstrasbourg.iot-lab.info",
  "y": "0",
  "z": "0",
  "mobility_type": "turtlebot2",
  "state": "Absent",
  "camera": 0,
  "archi": "m3:at86rf231"
}, {
  "uid": "a886",
  "site": "devstrasbourg",
  "x": "0",
  "mobile": 1,
  "network_address": "m3-90.devstrasbourg.iot-lab.info",
  "y": "0",
  "z": "0",
  "mobility_type": "turtlebot2",
  "state": "Absent",
  "camera": 0,
  "archi": "m3:at86rf231"
}, {
  "uid": " ",
  "site": "devstrasbourg",
  "x": "0",
  "mobile": 1,
  "network_address": "m3-91.devstrasbourg.iot-lab.info",
  "y": "0",
  "z": "0",
  "mobility_type": "turtlebot2",
  "state": "Absent",
  "camera": 0,
  "archi": "m3:at86rf231"
}, {
  "uid": " ",
  "site": "devstrasbourg",
  "x": "0",
  "mobile": 1,
  "network_address": "m3-92.devstrasbourg.iot-lab.info",
  "y": "0",
  "z": "0",
  "mobility_type": "turtlebot2",
  "state": "Absent",
  "camera": 0,
  "archi": "m3:at86rf231"
}, {
  "uid": " ",
  "site": "devstrasbourg",
  "x": "0",
  "mobile": 1,
  "network_address": "m3-93.devstrasbourg.iot-lab.info",
  "y": "0",
  "z": "0",
  "mobility_type": "turtlebot2",
  "state": "Absent",
  "camera": 0,
  "archi": "m3:at86rf231"
}, {
  "uid": " ",
  "site": "devstrasbourg",
  "x": "0",
  "mobile": 1,
  "network_address": "m3-94.devstrasbourg.iot-lab.info",
  "y": "0",
  "z": "0",
  "mobility_type": "turtlebot2",
  "state": "Absent",
  "camera": 0,
  "archi": "m3:at86rf231"
}, {
  "uid": " ",
  "site": "devstrasbourg",
  "x": "0",
  "mobile": 1,
  "network_address": "m3-102.devstrasbourg.iot-lab.info",
  "y": "0",
  "z": "0",
  "mobility_type": "turtlebot2",
  "state": "Alive",
  "camera": 0,
  "archi": "m3:at86rf231"
}, {
  "uid": "8884",
  "site": "devstrasbourg",
  "x": "0",
  "mobile": 0,
  "network_address": "m3-103.devstrasbourg.iot-lab.info",
  "y": "1",
  "z": "0",
  "mobility_type": " ",
  "state": "Alive",
  "camera": 0,
  "archi": "m3:at86rf231"
}, {
  "uid": "a087",
  "site": "devstrasbourg",
  "x": "0",
  "mobile": 0,
  "network_address": "m3-104.devstrasbourg.iot-lab.info",
  "y": "2",
  "z": "0",
  "mobility_type": " ",
  "state": "Alive",
  "camera": 0,
  "archi": "m3:at86rf231"
}, {
  "uid": "9886",
  "site": "devstrasbourg",
  "x": "0",
  "mobile": 0,
  "network_address": "m3-105.devstrasbourg.iot-lab.info",
  "y": "3",
  "z": "0",
  "mobility_type": " ",
  "state": "Alive",
  "camera": 0,
  "archi": "m3:at86rf231"
}, {
  "uid": " ",
  "site": "devgrenoble",
  "x": "7",
  "mobile": 0,
  "network_address": "fox-1.devgrenoble.iot-lab.info",
  "y": "0",
  "z": "0",
  "mobility_type": " ",
  "state": "Alive",
  "camera": 0,
  "archi": "fox:at86rf231"
}, {
  "uid": " ",
  "site": "devgrenoble",
  "x": "7",
  "mobile": 0,
  "network_address": "leonardo-1.devgrenoble.iot-lab.info",
  "y": "1",
  "z": "0",
  "mobility_type": " ",
  "state": "Alive",
  "camera": 0,
  "archi": "leonardo:"
}, {
  "uid": " ",
  "site": "devgrenoble",
  "x": "7",
  "mobile": 0,
  "network_address": "mega-1.devgrenoble.iot-lab.info",
  "y": "1",
  "z": "1",
  "mobility_type": " ",
  "state": "Alive",
  "camera": 0,
  "archi": "mega:"
}, {
  "uid": " ",
  "site": "devgrenoble",
  "x": "8",
  "mobile": 0,
  "network_address": "samr21-1.devgrenoble.iot-lab.info",
  "y": "0",
  "z": "0",
  "mobility_type": " ",
  "state": "Alive",
  "camera": 0,
  "archi": "samr21:at86rf233"
}, {
  "uid": " ",
  "site": "devgrenoble",
  "x": "3",
  "mobile": 0,
  "network_address": "openmote-1.devgrenoble.iot-lab.info",
  "y": "3",
  "z": "1",
  "mobility_type": " ",
  "state": "Suspected",
  "camera": 0,
  "archi": "openmote:cc2538"
}, {
  "uid": " ",
  "site": "devgrenoble",
  "x": "2",
  "mobile": 0,
  "network_address": "openmote-2.devgrenoble.iot-lab.info",
  "y": "3",
  "z": "1",
  "mobility_type": " ",
  "state": "Alive",
  "camera": 0,
  "archi": "openmote:cc2538"
}, {
  "uid": " ",
  "site": "devstrasbourg",
  "x": "0",
  "mobile": 0,
  "network_address": "zigduino-1.devstrasbourg.iot-lab.info",
  "y": "4",
  "z": "1",
  "mobility_type": " ",
  "state": "Alive",
  "camera": 0,
  "archi": "zigduino:atmega128rfa1"
}, {
  "uid": " ",
  "site": "devstrasbourg",
  "x": "0",
  "mobile": 0,
  "network_address": "arduino_zero-1.devstrasbourg.iot-lab.info",
  "y": "5",
  "z": "1",
  "mobility_type": " ",
  "state": "Alive",
  "camera": 0,
  "archi": "arduino_zero:"
}, {
  "uid": " ",
  "site": "devgrenoble",
  "x": "2",
  "mobile": 0,
  "network_address": "zigduino-1.devgrenoble.iot-lab.info",
  "y": "2",
  "z": "1",
  "mobility_type": " ",
  "state": "Alive",
  "camera": 0,
  "archi": "zigduino:atmega128rfa1"
}, {
  "uid": "1659",
  "site": "devlille",
  "x": " ",
  "mobile": 1,
  "network_address": "m3-201.devlille.iot-lab.info",
  "y": " ",
  "z": " ",
  "mobility_type": "turtlebot2",
  "state": "Absent",
  "camera": 0,
  "archi": "m3:at86rf231"
}, {
  "uid": "2351",
  "site": "devlille",
  "x": " ",
  "mobile": 1,
  "network_address": "m3-202.devlille.iot-lab.info",
  "y": " ",
  "z": " ",
  "mobility_type": "turtlebot2",
  "state": "Absent",
  "camera": 0,
  "archi": "m3:at86rf231"
}, {
  "uid": "2954",
  "site": "devlille",
  "x": " ",
  "mobile": 1,
  "network_address": "m3-203.devlille.iot-lab.info",
  "y": " ",
  "z": " ",
  "mobility_type": "turtlebot2",
  "state": "Alive",
  "camera": 0,
  "archi": "m3:at86rf231"
}, {
  "uid": "1557",
  "site": "devlille",
  "x": " ",
  "mobile": 1,
  "network_address": "m3-204.devlille.iot-lab.info",
  "y": " ",
  "z": " ",
  "mobility_type": "turtlebot2",
  "state": "Absent",
  "camera": 0,
  "archi": "m3:at86rf231"
}, {
  "uid": "b570",
  "site": "devlille",
  "x": " ",
  "mobile": 1,
  "network_address": "m3-205.devlille.iot-lab.info",
  "y": " ",
  "z": " ",
  "mobility_type": "turtlebot2",
  "state": "Absent",
  "camera": 0,
  "archi": "m3:at86rf231"
}, {
  "uid": "b072",
  "site": "devlille",
  "x": " ",
  "mobile": 1,
  "network_address": "m3-206.devlille.iot-lab.info",
  "y": " ",
  "z": " ",
  "mobility_type": "turtlebot2",
  "state": "Absent",
  "camera": 0,
  "archi": "m3:at86rf231"
}, {
  "uid": "uuuu",
  "site": "devlille",
  "x": " ",
  "mobile": 0,
  "network_address": "open_node-33.devlille.iot-lab.info",
  "y": " ",
  "z": " ",
  "mobility_type": " ",
  "state": "Suspected",
  "camera": 0,
  "archi": "open_node"
}, {
  "uid": "uuuu",
  "site": "devlille",
  "x": " ",
  "mobile": 0,
  "network_address": "open_node-34.devlille.iot-lab.info",
  "y": " ",
  "z": " ",
  "mobility_type": " ",
  "state": "Suspected",
  "camera": 0,
  "archi": "open_node"
}, {
  "uid": "uuuu",
  "site": "devlille",
  "x": " ",
  "mobile": 0,
  "network_address": "open_node-35.devlille.iot-lab.info",
  "y": " ",
  "z": " ",
  "mobility_type": " ",
  "state": "Suspected",
  "camera": 0,
  "archi": "open_node"
}, {
  "uid": "uuuu",
  "site": "devlille",
  "x": " ",
  "mobile": 0,
  "network_address": "open_node-36.devlille.iot-lab.info",
  "y": " ",
  "z": " ",
  "mobility_type": " ",
  "state": "Suspected",
  "camera": 0,
  "archi": "open_node"
}, {
  "uid": "uuuu",
  "site": "devlille",
  "x": " ",
  "mobile": 0,
  "network_address": "open_node-31.devlille.iot-lab.info",
  "y": " ",
  "z": " ",
  "mobility_type": " ",
  "state": "Suspected",
  "camera": 0,
  "archi": "open_node"
}, {
  "uid": "uuuu",
  "site": "devlille",
  "x": " ",
  "mobile": 0,
  "network_address": "open_node-32.devlille.iot-lab.info",
  "y": " ",
  "z": " ",
  "mobility_type": " ",
  "state": "Suspected",
  "camera": 0,
  "archi": "open_node"
}, {
  "uid": "uuuu",
  "site": "devlille",
  "x": " ",
  "mobile": 0,
  "network_address": "open_node-37.devlille.iot-lab.info",
  "y": " ",
  "z": " ",
  "mobility_type": " ",
  "state": "Suspected",
  "camera": 0,
  "archi": "open_node"
}, {
  "uid": "uuuu",
  "site": "devlille",
  "x": " ",
  "mobile": 0,
  "network_address": "open_node-38.devlille.iot-lab.info",
  "y": " ",
  "z": " ",
  "mobility_type": " ",
  "state": "Suspected",
  "camera": 0,
  "archi": "open_node"
}, {
  "uid": "uuuu",
  "site": "devlille",
  "x": " ",
  "mobile": 0,
  "network_address": "open_node-39.devlille.iot-lab.info",
  "y": " ",
  "z": " ",
  "mobility_type": " ",
  "state": "Suspected",
  "camera": 0,
  "archi": "open_node"
}, {
  "uid": "uuuu",
  "site": "devlille",
  "x": " ",
  "mobile": 0,
  "network_address": "open_node-40.devlille.iot-lab.info",
  "y": " ",
  "z": " ",
  "mobility_type": " ",
  "state": "Suspected",
  "camera": 0,
  "archi": "open_node"
}, {
  "uid": "uuuu",
  "site": "devlille",
  "x": " ",
  "mobile": 0,
  "network_address": "open_node-41.devlille.iot-lab.info",
  "y": " ",
  "z": " ",
  "mobility_type": " ",
  "state": "Suspected",
  "camera": 0,
  "archi": "open_node"
}, {
  "uid": "uuuu",
  "site": "devlille",
  "x": " ",
  "mobile": 0,
  "network_address": "open_node-42.devlille.iot-lab.info",
  "y": " ",
  "z": " ",
  "mobility_type": " ",
  "state": "Suspected",
  "camera": 0,
  "archi": "open_node"
}, {
  "uid": "uuuu",
  "site": "devlille",
  "x": " ",
  "mobile": 0,
  "network_address": "open_node-43.devlille.iot-lab.info",
  "y": " ",
  "z": " ",
  "mobility_type": " ",
  "state": "Suspected",
  "camera": 0,
  "archi": "open_node"
}, {
  "uid": "uuuu",
  "site": "devlille",
  "x": " ",
  "mobile": 0,
  "network_address": "open_node-44.devlille.iot-lab.info",
  "y": " ",
  "z": " ",
  "mobility_type": " ",
  "state": "Suspected",
  "camera": 0,
  "archi": "open_node"
}, {
  "uid": "uuuu",
  "site": "devlille",
  "x": " ",
  "mobile": 0,
  "network_address": "open_node-45.devlille.iot-lab.info",
  "y": " ",
  "z": " ",
  "mobility_type": " ",
  "state": "Suspected",
  "camera": 0,
  "archi": "open_node"
}, {
  "uid": "uuuu",
  "site": "devlille",
  "x": " ",
  "mobile": 0,
  "network_address": "open_node-46.devlille.iot-lab.info",
  "y": " ",
  "z": " ",
  "mobility_type": " ",
  "state": "Suspected",
  "camera": 0,
  "archi": "open_node"
}, {
  "uid": "uuuu",
  "site": "devlille",
  "x": " ",
  "mobile": 0,
  "network_address": "open_node-47.devlille.iot-lab.info",
  "y": " ",
  "z": " ",
  "mobility_type": " ",
  "state": "Suspected",
  "camera": 0,
  "archi": "open_node"
}, {
  "uid": "uuuu",
  "site": "devlille",
  "x": " ",
  "mobile": 0,
  "network_address": "open_node-48.devlille.iot-lab.info",
  "y": " ",
  "z": " ",
  "mobility_type": " ",
  "state": "Suspected",
  "camera": 0,
  "archi": "open_node"
}, {
  "uid": "uuuu",
  "site": "devlille",
  "x": " ",
  "mobile": 0,
  "network_address": "open_node-49.devlille.iot-lab.info",
  "y": " ",
  "z": " ",
  "mobility_type": " ",
  "state": "Suspected",
  "camera": 0,
  "archi": "open_node"
}, {
  "uid": "uuuu",
  "site": "devlille",
  "x": " ",
  "mobile": 0,
  "network_address": "open_node-50.devlille.iot-lab.info",
  "y": " ",
  "z": " ",
  "mobility_type": " ",
  "state": "Suspected",
  "camera": 0,
  "archi": "open_node"
}, {
  "uid": "uuuu",
  "site": "devlille",
  "x": " ",
  "mobile": 0,
  "network_address": "open_node-51.devlille.iot-lab.info",
  "y": " ",
  "z": " ",
  "mobility_type": " ",
  "state": "Suspected",
  "camera": 0,
  "archi": "open_node"
}, {
  "uid": "uuuu",
  "site": "devlille",
  "x": " ",
  "mobile": 0,
  "network_address": "open_node-52.devlille.iot-lab.info",
  "y": " ",
  "z": " ",
  "mobility_type": " ",
  "state": "Suspected",
  "camera": 0,
  "archi": "open_node"
}, {
  "uid": "uuuu",
  "site": "devlille",
  "x": " ",
  "mobile": 0,
  "network_address": "open_node-53.devlille.iot-lab.info",
  "y": " ",
  "z": " ",
  "mobility_type": " ",
  "state": "Suspected",
  "camera": 0,
  "archi": "open_node"
}, {
  "uid": "uuuu",
  "site": "devlille",
  "x": " ",
  "mobile": 0,
  "network_address": "open_node-54.devlille.iot-lab.info",
  "y": " ",
  "z": " ",
  "mobility_type": " ",
  "state": "Suspected",
  "camera": 0,
  "archi": "open_node"
}, {
  "uid": "uuuu",
  "site": "devlille",
  "x": " ",
  "mobile": 0,
  "network_address": "open_node-55.devlille.iot-lab.info",
  "y": " ",
  "z": " ",
  "mobility_type": " ",
  "state": "Suspected",
  "camera": 0,
  "archi": "open_node"
}, {
  "uid": "uuuu",
  "site": "devlille",
  "x": " ",
  "mobile": 0,
  "network_address": "open_node-56.devlille.iot-lab.info",
  "y": " ",
  "z": " ",
  "mobility_type": " ",
  "state": "Suspected",
  "camera": 0,
  "archi": "open_node"
}, {
  "uid": "uuuu",
  "site": "devlille",
  "x": " ",
  "mobile": 0,
  "network_address": "open_node-57.devlille.iot-lab.info",
  "y": " ",
  "z": " ",
  "mobility_type": " ",
  "state": "Suspected",
  "camera": 0,
  "archi": "open_node"
}, {
  "uid": "uuuu",
  "site": "devlille",
  "x": " ",
  "mobile": 0,
  "network_address": "open_node-58.devlille.iot-lab.info",
  "y": " ",
  "z": " ",
  "mobility_type": " ",
  "state": "Suspected",
  "camera": 0,
  "archi": "open_node"
}, {
  "uid": "uuuu",
  "site": "devlille",
  "x": " ",
  "mobile": 0,
  "network_address": "open_node-59.devlille.iot-lab.info",
  "y": " ",
  "z": " ",
  "mobility_type": " ",
  "state": "Suspected",
  "camera": 0,
  "archi": "open_node"
}, {
  "uid": "uuuu",
  "site": "devlille",
  "x": " ",
  "mobile": 0,
  "network_address": "open_node-60.devlille.iot-lab.info",
  "y": " ",
  "z": " ",
  "mobility_type": " ",
  "state": "Suspected",
  "camera": 0,
  "archi": "open_node"
}, {
  "uid": "uuuu",
  "site": "devlille",
  "x": " ",
  "mobile": 0,
  "network_address": "open_node-61.devlille.iot-lab.info",
  "y": " ",
  "z": " ",
  "mobility_type": " ",
  "state": "Suspected",
  "camera": 0,
  "archi": "open_node"
}, {
  "uid": "uuuu",
  "site": "devlille",
  "x": " ",
  "mobile": 0,
  "network_address": "open_node-62.devlille.iot-lab.info",
  "y": " ",
  "z": " ",
  "mobility_type": " ",
  "state": "Suspected",
  "camera": 0,
  "archi": "open_node"
}, {
  "uid": "uuuu",
  "site": "devlille",
  "x": " ",
  "mobile": 0,
  "network_address": "open_node-63.devlille.iot-lab.info",
  "y": " ",
  "z": " ",
  "mobility_type": " ",
  "state": "Suspected",
  "camera": 0,
  "archi": "open_node"
}, {
  "uid": "uuuu",
  "site": "devlille",
  "x": " ",
  "mobile": 0,
  "network_address": "open_node-64.devlille.iot-lab.info",
  "y": " ",
  "z": " ",
  "mobility_type": " ",
  "state": "Suspected",
  "camera": 0,
  "archi": "open_node"
}, {
  "uid": "uuuu",
  "site": "devlille",
  "x": " ",
  "mobile": 0,
  "network_address": "open_node-65.devlille.iot-lab.info",
  "y": " ",
  "z": " ",
  "mobility_type": " ",
  "state": "Suspected",
  "camera": 0,
  "archi": "open_node"
}, {
  "uid": "uuuu",
  "site": "devlille",
  "x": " ",
  "mobile": 0,
  "network_address": "open_node-66.devlille.iot-lab.info",
  "y": " ",
  "z": " ",
  "mobility_type": " ",
  "state": "Suspected",
  "camera": 0,
  "archi": "open_node"
}, {
  "uid": "uuuu",
  "site": "devlille",
  "x": " ",
  "mobile": 0,
  "network_address": "open_node-67.devlille.iot-lab.info",
  "y": " ",
  "z": " ",
  "mobility_type": " ",
  "state": "Suspected",
  "camera": 0,
  "archi": "open_node"
}, {
  "uid": "uuuu",
  "site": "devlille",
  "x": " ",
  "mobile": 0,
  "network_address": "open_node-68.devlille.iot-lab.info",
  "y": " ",
  "z": " ",
  "mobility_type": " ",
  "state": "Suspected",
  "camera": 0,
  "archi": "open_node"
}, {
  "uid": "uuuu",
  "site": "devlille",
  "x": " ",
  "mobile": 0,
  "network_address": "open_node-69.devlille.iot-lab.info",
  "y": " ",
  "z": " ",
  "mobility_type": " ",
  "state": "Suspected",
  "camera": 0,
  "archi": "open_node"
}, {
  "uid": "b160",
  "site": "devsaclay",
  "x": "2",
  "mobile": 0,
  "network_address": "a8-1.devsaclay.iot-lab.info",
  "y": "0",
  "z": "0",
  "mobility_type": " ",
  "state": "Alive",
  "camera": 0,
  "archi": "a8:at86rf231"
}, {
  "uid": " ",
  "site": "devsaclay",
  "x": "5",
  "mobile": 0,
  "network_address": "m3-1.devsaclay.iot-lab.info",
  "y": "65.3",
  "z": "4",
  "mobility_type": " ",
  "state": "Alive",
  "camera": 1,
  "archi": "m3:at86rf231"
}, {
  "uid": " ",
  "site": "devsaclay",
  "x": "0.8",
  "mobile": 0,
  "network_address": "microbit-1.devsaclay.iot-lab.info",
  "y": "64.3",
  "z": "4",
  "mobility_type": " ",
  "state": "Alive",
  "camera": 0,
  "archi": "microbit:ble"
}, {
  "uid": " ",
  "site": "devsaclay",
  "x": "1.8",
  "mobile": 0,
  "network_address": "arduino-zero-1.devsaclay.iot-lab.info",
  "y": "64.3",
  "z": "4",
  "mobility_type": " ",
  "state": "Alive",
  "camera": 0,
  "archi": "arduino-zero:xbee"
}, {
  "uid": " ",
  "site": "devsaclay",
  "x": "4",
  "mobile": 0,
  "network_address": "st-lrwan1-1.devsaclay.iot-lab.info",
  "y": "65.3",
  "z": "4",
  "mobility_type": " ",
  "state": "Alive",
  "camera": 0,
  "archi": "st-lrwan1:sx1276"
}, {
  "uid": "1659",
  "site": "devlille",
  "x": " ",
  "mobile": 0,
  "network_address": "microbit-1.devlille.iot-lab.info",
  "y": " ",
  "z": " ",
  "mobility_type": " ",
  "state": "Alive",
  "camera": 0,
  "archi": "microbit"
}, {
  "uid": "1659",
  "site": "devlille",
  "x": " ",
  "mobile": 0,
  "network_address": "microbit-2.devlille.iot-lab.info",
  "y": " ",
  "z": " ",
  "mobility_type": " ",
  "state": "Alive",
  "camera": 0,
  "archi": "microbit"
}, {
  "uid": "1659",
  "site": "devlille",
  "x": " ",
  "mobile": 0,
  "network_address": "st_lrwan1-1.devlille.iot-lab.info",
  "y": " ",
  "z": " ",
  "mobility_type": " ",
  "state": "Alive",
  "camera": 0,
  "archi": "st_lrwan1"
}, {
  "uid": "1659",
  "site": "devlille",
  "x": " ",
  "mobile": 0,
  "network_address": "st_lrwan1-2.devlille.iot-lab.info",
  "y": " ",
  "z": " ",
  "mobility_type": " ",
  "state": "Alive",
  "camera": 0,
  "archi": "st_lrwan1"
}, {
  "uid": "uuuu",
  "site": "devlille",
  "x": " ",
  "mobile": 0,
  "network_address": "open_node-1.devlille.iot-lab.info",
  "y": " ",
  "z": " ",
  "mobility_type": " ",
  "state": "Suspected",
  "camera": 0,
  "archi": "open_node"
}, {
  "uid": "uuuu",
  "site": "devlille",
  "x": " ",
  "mobile": 0,
  "network_address": "open_node-2.devlille.iot-lab.info",
  "y": " ",
  "z": " ",
  "mobility_type": " ",
  "state": "Suspected",
  "camera": 0,
  "archi": "open_node"
}, {
  "uid": "uuuu",
  "site": "devlille",
  "x": " ",
  "mobile": 0,
  "network_address": "open_node-3.devlille.iot-lab.info",
  "y": " ",
  "z": " ",
  "mobility_type": " ",
  "state": "Suspected",
  "camera": 0,
  "archi": "open_node"
}, {
  "uid": "uuuu",
  "site": "devlille",
  "x": " ",
  "mobile": 0,
  "network_address": "open_node-4.devlille.iot-lab.info",
  "y": " ",
  "z": " ",
  "mobility_type": " ",
  "state": "Suspected",
  "camera": 0,
  "archi": "open_node"
}, {
  "uid": "uuuu",
  "site": "devlille",
  "x": " ",
  "mobile": 0,
  "network_address": "open_node-5.devlille.iot-lab.info",
  "y": " ",
  "z": " ",
  "mobility_type": " ",
  "state": "Suspected",
  "camera": 0,
  "archi": "open_node"
}, {
  "uid": "uuuu",
  "site": "devlille",
  "x": " ",
  "mobile": 0,
  "network_address": "open_node-6.devlille.iot-lab.info",
  "y": " ",
  "z": " ",
  "mobility_type": " ",
  "state": "Suspected",
  "camera": 0,
  "archi": "open_node"
}, {
  "uid": "uuuu",
  "site": "devlille",
  "x": " ",
  "mobile": 0,
  "network_address": "open_node-7.devlille.iot-lab.info",
  "y": " ",
  "z": " ",
  "mobility_type": " ",
  "state": "Suspected",
  "camera": 0,
  "archi": "open_node"
}, {
  "uid": "uuuu",
  "site": "devlille",
  "x": " ",
  "mobile": 0,
  "network_address": "open_node-8.devlille.iot-lab.info",
  "y": " ",
  "z": " ",
  "mobility_type": " ",
  "state": "Alive",
  "camera": 0,
  "archi": "open_node"
}, {
  "uid": "uuuu",
  "site": "devlille",
  "x": " ",
  "mobile": 0,
  "network_address": "open_node-9.devlille.iot-lab.info",
  "y": " ",
  "z": " ",
  "mobility_type": " ",
  "state": "Alive",
  "camera": 0,
  "archi": "open_node"
}, {
  "uid": "uuuu",
  "site": "devlille",
  "x": " ",
  "mobile": 0,
  "network_address": "open_node-10.devlille.iot-lab.info",
  "y": " ",
  "z": " ",
  "mobility_type": " ",
  "state": "Suspected",
  "camera": 0,
  "archi": "open_node"
}, {
  "uid": "uuuu",
  "site": "devlille",
  "x": " ",
  "mobile": 0,
  "network_address": "open_node-11.devlille.iot-lab.info",
  "y": " ",
  "z": " ",
  "mobility_type": " ",
  "state": "Suspected",
  "camera": 0,
  "archi": "open_node"
}, {
  "uid": "uuuu",
  "site": "devlille",
  "x": " ",
  "mobile": 0,
  "network_address": "open_node-12.devlille.iot-lab.info",
  "y": " ",
  "z": " ",
  "mobility_type": " ",
  "state": "Suspected",
  "camera": 0,
  "archi": "open_node"
}, {
  "uid": "uuuu",
  "site": "devlille",
  "x": " ",
  "mobile": 0,
  "network_address": "open_node-13.devlille.iot-lab.info",
  "y": " ",
  "z": " ",
  "mobility_type": " ",
  "state": "Suspected",
  "camera": 0,
  "archi": "open_node"
}, {
  "uid": "uuuu",
  "site": "devlille",
  "x": " ",
  "mobile": 0,
  "network_address": "open_node-14.devlille.iot-lab.info",
  "y": " ",
  "z": " ",
  "mobility_type": " ",
  "state": "Suspected",
  "camera": 0,
  "archi": "open_node"
}, {
  "uid": "uuuu",
  "site": "devlille",
  "x": " ",
  "mobile": 0,
  "network_address": "open_node-15.devlille.iot-lab.info",
  "y": " ",
  "z": " ",
  "mobility_type": " ",
  "state": "Suspected",
  "camera": 0,
  "archi": "open_node"
}, {
  "uid": "uuuu",
  "site": "devlille",
  "x": " ",
  "mobile": 0,
  "network_address": "open_node-16.devlille.iot-lab.info",
  "y": " ",
  "z": " ",
  "mobility_type": " ",
  "state": "Suspected",
  "camera": 0,
  "archi": "open_node"
}, {
  "uid": "uuuu",
  "site": "devlille",
  "x": " ",
  "mobile": 0,
  "network_address": "open_node-17.devlille.iot-lab.info",
  "y": " ",
  "z": " ",
  "mobility_type": " ",
  "state": "Suspected",
  "camera": 0,
  "archi": "open_node"
}, {
  "uid": "uuuu",
  "site": "devlille",
  "x": " ",
  "mobile": 0,
  "network_address": "open_node-18.devlille.iot-lab.info",
  "y": " ",
  "z": " ",
  "mobility_type": " ",
  "state": "Suspected",
  "camera": 0,
  "archi": "open_node"
}, {
  "uid": "uuuu",
  "site": "devlille",
  "x": " ",
  "mobile": 0,
  "network_address": "open_node-19.devlille.iot-lab.info",
  "y": " ",
  "z": " ",
  "mobility_type": " ",
  "state": "Suspected",
  "camera": 0,
  "archi": "open_node"
}, {
  "uid": "uuuu",
  "site": "devlille",
  "x": " ",
  "mobile": 0,
  "network_address": "open_node-20.devlille.iot-lab.info",
  "y": " ",
  "z": " ",
  "mobility_type": " ",
  "state": "Suspected",
  "camera": 0,
  "archi": "open_node"
}, {
  "uid": "uuuu",
  "site": "devlille",
  "x": " ",
  "mobile": 0,
  "network_address": "open_node-21.devlille.iot-lab.info",
  "y": " ",
  "z": " ",
  "mobility_type": " ",
  "state": "Suspected",
  "camera": 0,
  "archi": "open_node"
}, {
  "uid": "uuuu",
  "site": "devlille",
  "x": " ",
  "mobile": 0,
  "network_address": "open_node-22.devlille.iot-lab.info",
  "y": " ",
  "z": " ",
  "mobility_type": " ",
  "state": "Suspected",
  "camera": 0,
  "archi": "open_node"
}, {
  "uid": "uuuu",
  "site": "devlille",
  "x": " ",
  "mobile": 0,
  "network_address": "open_node-23.devlille.iot-lab.info",
  "y": " ",
  "z": " ",
  "mobility_type": " ",
  "state": "Suspected",
  "camera": 0,
  "archi": "open_node"
}, {
  "uid": "uuuu",
  "site": "devlille",
  "x": " ",
  "mobile": 0,
  "network_address": "open_node-24.devlille.iot-lab.info",
  "y": " ",
  "z": " ",
  "mobility_type": " ",
  "state": "Suspected",
  "camera": 0,
  "archi": "open_node"
}, {
  "uid": "uuuu",
  "site": "devlille",
  "x": " ",
  "mobile": 0,
  "network_address": "open_node-25.devlille.iot-lab.info",
  "y": " ",
  "z": " ",
  "mobility_type": " ",
  "state": "Suspected",
  "camera": 0,
  "archi": "open_node"
}, {
  "uid": "uuuu",
  "site": "devlille",
  "x": " ",
  "mobile": 0,
  "network_address": "open_node-26.devlille.iot-lab.info",
  "y": " ",
  "z": " ",
  "mobility_type": " ",
  "state": "Suspected",
  "camera": 0,
  "archi": "open_node"
}, {
  "uid": "uuuu",
  "site": "devlille",
  "x": " ",
  "mobile": 0,
  "network_address": "open_node-27.devlille.iot-lab.info",
  "y": " ",
  "z": " ",
  "mobility_type": " ",
  "state": "Suspected",
  "camera": 0,
  "archi": "open_node"
}, {
  "uid": "uuuu",
  "site": "devlille",
  "x": " ",
  "mobile": 0,
  "network_address": "open_node-28.devlille.iot-lab.info",
  "y": " ",
  "z": " ",
  "mobility_type": " ",
  "state": "Suspected",
  "camera": 0,
  "archi": "open_node"
}, {
  "uid": "uuuu",
  "site": "devlille",
  "x": " ",
  "mobile": 0,
  "network_address": "open_node-29.devlille.iot-lab.info",
  "y": " ",
  "z": " ",
  "mobility_type": " ",
  "state": "Suspected",
  "camera": 0,
  "archi": "open_node"
}, {
  "uid": "uuuu",
  "site": "devlille",
  "x": " ",
  "mobile": 0,
  "network_address": "open_node-30.devlille.iot-lab.info",
  "y": " ",
  "z": " ",
  "mobility_type": " ",
  "state": "Suspected",
  "camera": 0,
  "archi": "open_node"
}, {
  "uid": " ",
  "site": "devsaclay",
  "x": "2.8",
  "mobile": 0,
  "network_address": "st-lrwan1-2.devsaclay.iot-lab.info",
  "y": "64.3",
  "z": "4",
  "mobility_type": " ",
  "state": "Alive",
  "camera": 0,
  "archi": "st-lrwan1:sx1276"
}, {
  "uid": " ",
  "site": "devsaclay",
  "x": "3.8",
  "mobile": 0,
  "network_address": "nrf52dk-1.devsaclay.iot-lab.info",
  "y": "64.3",
  "z": "4",
  "mobility_type": " ",
  "state": "Alive",
  "camera": 0,
  "archi": "nrf52dk:ble"
}, {
  "uid": " ",
  "site": "devsaclay",
  "x": "3",
  "mobile": 0,
  "network_address": "nrf52dk-2.devsaclay.iot-lab.info",
  "y": "65.3",
  "z": "4",
  "mobility_type": " ",
  "state": "Alive",
  "camera": 0,
  "archi": "nrf52dk:ble"
}, {
  "uid": " ",
  "site": "devsaclay",
  "x": "1.8",
  "mobile": 0,
  "network_address": "microbit-2.devsaclay.iot-lab.info",
  "y": "65.3",
  "z": "4",
  "mobility_type": " ",
  "state": "Alive",
  "camera": 0,
  "archi": "microbit:ble"
}, {
  "uid": " ",
  "site": "devsaclay",
  "x": "0.8",
  "mobile": 0,
  "network_address": "st-iotnode-1.devsaclay.iot-lab.info",
  "y": "65.3",
  "z": "4",
  "mobility_type": " ",
  "state": "Alive",
  "camera": 0,
  "archi": "st-iotnode:multi"
}, {
  "uid": " ",
  "site": "devsaclay",
  "x": "4.8",
  "mobile": 0,
  "network_address": "nrf52840dk-1.devsaclay.iot-lab.info",
  "y": "64.3",
  "z": "4",
  "mobility_type": " ",
  "state": "Alive",
  "camera": 0,
  "archi": "nrf52840dk:ble"
}])
iotlab.getSitesDetails = jest.fn().mockResolvedValue([{"site":"devgrenoble","archis":[{"archi":"a8:at86rf231","mobile":0,"total":12},{"archi":"fox:at86rf231","mobile":0,"total":1},{"archi":"des:wifi-cc1100","mobile":0,"total":1},{"archi":"m3:at86rf231","mobile":2,"total":17},{"archi":"openmote:cc2538","mobile":0,"total":2},{"archi":"mega:","mobile":0,"total":1},{"archi":"samr21:at86rf233","mobile":0,"total":1},{"archi":"leonardo:","mobile":0,"total":1},{"archi":"zigduino:atmega128rfa1","mobile":0,"total":1}]},{"site":"devlille","archis":[{"archi":"microbit","mobile":0,"total":2},{"archi":"m3:at86rf231","mobile":6,"total":6},{"archi":"st_lrwan1","mobile":0,"total":2},{"archi":"open_node","mobile":0,"total":69}]},{"site":"devsaclay","archis":[{"archi":"nrf52dk:ble","mobile":0,"total":2},{"archi":"a8:at86rf231","mobile":0,"total":1},{"archi":"arduino-zero:xbee","mobile":0,"total":1},{"archi":"m3:at86rf231","mobile":0,"total":1},{"archi":"st-iotnode:multi","mobile":0,"total":1},{"archi":"microbit:ble","mobile":0,"total":2},{"archi":"st-lrwan1:sx1276","mobile":0,"total":2},{"archi":"nrf52840dk:ble","mobile":0,"total":1}]},{"site":"devstrasbourg","archis":[{"archi":"a8:at86rf231","mobile":0,"total":2},{"archi":"m3:at86rf231","mobile":27,"total":30},{"archi":"arduino_zero:","mobile":0,"total":1},{"archi":"wsn430:cc1101","mobile":0,"total":4},{"archi":"zigduino:atmega128rfa1","mobile":0,"total":1}]}])
iotlab.getRunningExperiments = jest.fn().mockResolvedValue([{"submitted_duration":20,"submission_date":"2018-09-25T15:02:57Z","nodes":["m3-12.devgrenoble.iot-lab.info","m3-10.devgrenoble.iot-lab.info","m3-13.devgrenoble.iot-lab.info"],"nb_nodes":3,"effective_duration":10,"name":"","stop_date":"1970-01-01T00:00:00Z","id":13308,"state":"Running","scheduled_date":"2018-09-25T15:02:58Z","user":"bformet","start_date":"2018-09-25T15:02:58Z"},{"submitted_duration":60,"submission_date":"2018-09-25T15:03:03Z","nodes":["a8-1.devgrenoble.iot-lab.info","a8-4.devgrenoble.iot-lab.info","a8-17.devgrenoble.iot-lab.info","a8-3.devgrenoble.iot-lab.info","a8-5.devgrenoble.iot-lab.info","a8-7.devgrenoble.iot-lab.info","a8-9.devgrenoble.iot-lab.info","a8-6.devgrenoble.iot-lab.info","a8-2.devgrenoble.iot-lab.info","a8-8.devgrenoble.iot-lab.info"],"nb_nodes":10,"effective_duration":10,"name":"","stop_date":"1970-01-01T00:00:00Z","id":13309,"state":"Running","scheduled_date":"2018-09-25T15:03:04Z","user":"bformet","start_date":"2018-09-25T15:03:04Z"}])

const router = new VueRouter()
const localVue = createLocalVue()
localVue.use(VueRouter)
localVue.filter('formatArchi', Filters.formatArchi)

describe('Status.vue', () => {

  it('should match snapshot', () => {
    const wrapper = shallowMount(Status, {localVue, router})
    expect(wrapper.element).toBeDefined()
    expect(wrapper.element).toMatchSnapshot()
  })

})
