name: CI

on:
  push:
    branches:
      - master
    tags:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  node-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [13.x, 14.x]
    steps:
    - uses: actions/set-timezone-action@v1.1
      with:
        timezoneLinux: "Europe/Paris"
    - uses: actions/checkout@master
    - name: setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: install and run Xvfb
      run: |
        sudo apt-get install xvfb
        export DISPLAY=:99
        Xvfb $DISPLAY &
    - name: npm install and test
      run: |
        npm install
        npm run test:unit
        npm run test:e2e -- --headless
